### ISSUE TITLE
Wordpress install in specific directory?

### ISSUE THREAD

**Issue by violacase** [michaelbromley/angular-wordpress-seed#2]
I always install wordpress in the root of the site. I suppose your demo wants me to put wordpress in a . ./wordpress/ map?

**Comment by violacase** [comment]
Any update?

**Comment by michaelbromley** [comment]
Hi,

You can put Wordpress wherever you like - you just need to update the path [in the config file](https://github.com/michaelbromley/angular-wordpress-seed/blob/master/config.json#L6) to point to that location.

Putting it in the root, however, may cause an issue if the wordpress index is served instead of the angular app index. I think it'll depend on how your server is configured.

**Comment by violacase** [comment]
Had a problem indeed with the conflicting index.php from wordpress in the root.
I see now... How nice! I'm just beginning to learn Angular so the concept wasn't too clear to me yet.
Can't wait to get further going. Thanks for now.
