### ISSUE TITLE
Uncaught ReferenceError: angular is not defined

### ISSUE THREAD

**Issue by viankakrisna** [michaelbromley/angular-wordpress-seed#3]
This happened after I follow the instruction. Upon examination, I saw that angular is not included anywhere in the file. Do we need to include it manually?

**Comment by michaelbromley** [comment]
Hi,

Angular is defined as a dependency in the Bower file: https://github.com/michaelbromley/angular-wordpress-seed/blob/master/bower.json#L23

That's why the instructions include to run `bower install`. If you haven't used Bower before, try reading up on it here: http://bower.io/. 

Hope that helps,

Michael

**Comment by viankakrisna** [comment]
Whoops, my bad, thank you for the help. It is up and running beautifully now! :)
