### ISSUE TITLE
Static pages for custom posts not working

### ISSUE THREAD

**Issue by yougotashovel** [michaelbromley/angular-wordpress-seed#5]
How does the RewriteRule work for static-page.php and how does it detect the user agent?

I've tried adding in another RewriteRule for a custom post type i have named 'events':

 `RewriteRule events/(\d*)/.*$ %%SITE_URL%%/static-page.php?id=$1 [P]`

When directly visiting a link e.g: `domain.com/events/92/post-title`  I just get the static page in the browser, instead of the app page.  Any idea what's going on?

Thanks

**Comment by michaelbromley** [comment]
Hi,

Sorry - this issue got lost is the mists somehow. Your question seems to be a general "how do apache rewrite rules work?". I'm no expert but I'll attempt to explain as best I understand:

```
# allow social media crawlers to work by redirecting them to a server-rendered static version on the page
RewriteCond %{HTTP_USER_AGENT} (facebookexternalhit/[0-9]|Twitterbot|Pinterest|Google.*snippet|Googlebot|redditbot|bingbot)
RewriteRule blog/(\d*)/.*$ %%SITE_URL%%static-page.php?id=$1 [P]
```

So, the first line is a `RewriteCond` - it is like an "if" statement - if this is true, do the next line. If not, skip it. This is saying "if the user agent matches the following regex, execute the next line". This is how we do user-agent detection.

The next line does the actual rewrite. It says "if the requested URL matches the regex `blog/(\d*)/.*$`, then rewrite it to `[site url]/static-page.php?id=[whatever digits were captured by the regex]`. The [P] means do a "proxy pass" so that the URL does not need to change from the user-agent's point of view.

So in your last example, you don't have the initial `RewriteCond` in place, which is why you were being redirected, even from a browser.
