### ISSUE TITLE
Add dist folder

### ISSUE THREAD

**Issue by klihelp** [michaelbromley/angular-wordpress-seed#6]
Can you add dist folder to github?
I am not able to use and install node.

**Comment by michaelbromley** [comment]
I'm not going to add it to the repo, because it's not generally useful - you would have to do a lot of manual finding and replacing to modify anything. However, if you email me via this form http://www.michaelbromley.co.uk/contact I can send you the files.

Out of interest, why can you not use node?

**Comment by klihelp** [comment]
thanks:) sent you a mail @michaelbromley
I am limited how to use my brother's laptop.
